package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private String addCode;
	private String personId;
	private String address1;
	private String street;
	private String houseNo;
	private String pin;
	private String refAddress;
	private Date creDate;
	private String country;
	private Set personDependentDetails = new HashSet(0);

	public Address() {
	}

	public Address(String addCode) {
		this.addCode = addCode;
	}

	public Address(String addCode, String personId, String address1,
			String street, String houseNo, String pin, String refAddress,
			Date creDate, String country, Set personDependentDetails) {
		this.addCode = addCode;
		this.personId = personId;
		this.address1 = address1;
		this.street = street;
		this.houseNo = houseNo;
		this.pin = pin;
		this.refAddress = refAddress;
		this.creDate = creDate;
		this.country = country;
		this.personDependentDetails = personDependentDetails;
	}

	public String getAddCode() {
		return this.addCode;
	}

	public void setAddCode(String addCode) {
		this.addCode = addCode;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getHouseNo() {
		return this.houseNo;
	}

	public void setHouseNo(String houseNo) {
		this.houseNo = houseNo;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getRefAddress() {
		return this.refAddress;
	}

	public void setRefAddress(String refAddress) {
		this.refAddress = refAddress;
	}

	public Date getCreDate() {
		return this.creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getPersonDependentDetails() {
		return this.personDependentDetails;
	}

	public void setPersonDependentDetails(Set personDependentDetails) {
		this.personDependentDetails = personDependentDetails;
	}

}
