package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Calender generated by hbm2java
 */
public class Calender implements java.io.Serializable {

	private String code;
	private Date date;
	private String description;
	private String isNationalHoliday;

	public Calender() {
	}

	public Calender(String code) {
		this.code = code;
	}

	public Calender(String code, Date date, String description,
			String isNationalHoliday) {
		this.code = code;
		this.date = date;
		this.description = description;
		this.isNationalHoliday = isNationalHoliday;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIsNationalHoliday() {
		return this.isNationalHoliday;
	}

	public void setIsNationalHoliday(String isNationalHoliday) {
		this.isNationalHoliday = isNationalHoliday;
	}

}
