package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private String categoryType;
	private String category;
	private Set markses = new HashSet(0);
	private Set persons = new HashSet(0);
	private Set dailyWorks = new HashSet(0);
	private Set personDependentDetails = new HashSet(0);

	public Category() {
	}

	public Category(String categoryType) {
		this.categoryType = categoryType;
	}

	public Category(String categoryType, String category, Set markses,
			Set persons, Set dailyWorks, Set personDependentDetails) {
		this.categoryType = categoryType;
		this.category = category;
		this.markses = markses;
		this.persons = persons;
		this.dailyWorks = dailyWorks;
		this.personDependentDetails = personDependentDetails;
	}

	public String getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set markses) {
		this.markses = markses;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	public Set getDailyWorks() {
		return this.dailyWorks;
	}

	public void setDailyWorks(Set dailyWorks) {
		this.dailyWorks = dailyWorks;
	}

	public Set getPersonDependentDetails() {
		return this.personDependentDetails;
	}

	public void setPersonDependentDetails(Set personDependentDetails) {
		this.personDependentDetails = personDependentDetails;
	}

}
