package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Complexity generated by hbm2java
 */
public class Complexity implements java.io.Serializable {

	private String complexityType;

	public Complexity() {
	}

	public Complexity(String complexityType) {
		this.complexityType = complexityType;
	}

	public String getComplexityType() {
		return this.complexityType;
	}

	public void setComplexityType(String complexityType) {
		this.complexityType = complexityType;
	}

}
