package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * DailyWork generated by hbm2java
 */
public class DailyWork implements java.io.Serializable {

	private DailyWorkId id;
	private Person person;
	private Task task;
	private Category category;
	private Subject subject;
	private String remarks;

	public DailyWork() {
	}

	public DailyWork(DailyWorkId id, Person person, Category category,
			Subject subject) {
		this.id = id;
		this.person = person;
		this.category = category;
		this.subject = subject;
	}

	public DailyWork(DailyWorkId id, Person person, Task task,
			Category category, Subject subject, String remarks) {
		this.id = id;
		this.person = person;
		this.task = task;
		this.category = category;
		this.subject = subject;
		this.remarks = remarks;
	}

	public DailyWorkId getId() {
		return this.id;
	}

	public void setId(DailyWorkId id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
