package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private String eventType;
	private String eventName;
	private Set newsAndEventses = new HashSet(0);

	public Event() {
	}

	public Event(String eventType) {
		this.eventType = eventType;
	}

	public Event(String eventType, String eventName, Set newsAndEventses) {
		this.eventType = eventType;
		this.eventName = eventName;
		this.newsAndEventses = newsAndEventses;
	}

	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public Set getNewsAndEventses() {
		return this.newsAndEventses;
	}

	public void setNewsAndEventses(Set newsAndEventses) {
		this.newsAndEventses = newsAndEventses;
	}

}
