package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import java.util.Date;

/**
 * ExamSchedule generated by hbm2java
 */
public class ExamSchedule implements java.io.Serializable {

	private String scheduleId;
	private Classlevel classlevel;
	private Exam exam;
	private Date examStartDt;
	private Date examEndDt;
	private Set markses = new HashSet(0);
	private PerformanceType performanceType;

	public ExamSchedule() {
		classlevel = new Classlevel();
		exam = new Exam();
		
	}

	public ExamSchedule(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public ExamSchedule(String scheduleId, Classlevel classlevel, Exam exam,
			Date examStartDt, Date examEndDt, Set markses,
			PerformanceType performanceType) {
		this.scheduleId = scheduleId;
		this.classlevel = classlevel;
		this.exam = exam;
		this.examStartDt = examStartDt;
		this.examEndDt = examEndDt;
		this.markses = markses;
		this.performanceType = performanceType;
	}

	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Classlevel getClasslevel() {
		return this.classlevel;
	}

	public void setClasslevel(Classlevel classlevel) {
		this.classlevel = classlevel;
	}

	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	public Date getExamStartDt() {
		return this.examStartDt;
	}

	public void setExamStartDt(Date examStartDt) {
		this.examStartDt = examStartDt;
	}

	public Date getExamEndDt() {
		return this.examEndDt;
	}

	public void setExamEndDt(Date examEndDt) {
		this.examEndDt = examEndDt;
	}

	public Set getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set markses) {
		this.markses = markses;
	}

	public PerformanceType getPerformanceType() {
		return this.performanceType;
	}

	public void setPerformanceType(PerformanceType performanceType) {
		this.performanceType = performanceType;
	}

}
