package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Format generated by hbm2java
 */
public class Format implements java.io.Serializable {

	private String formatType;

	public Format() {
	}

	public Format(String formatType) {
		this.formatType = formatType;
	}

	public String getFormatType() {
		return this.formatType;
	}

	public void setFormatType(String formatType) {
		this.formatType = formatType;
	}

}
