package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Grades generated by hbm2java
 */
public class Grades implements java.io.Serializable {

	private String gradeType;
	private Float percentage;
	private Date latestUpdateDt;
	private String description;

	public Grades() {
	}

	public Grades(String gradeType) {
		this.gradeType = gradeType;
	}

	public Grades(String gradeType, Float percentage, Date latestUpdateDt,
			String description) {
		this.gradeType = gradeType;
		this.percentage = percentage;
		this.latestUpdateDt = latestUpdateDt;
		this.description = description;
	}

	public String getGradeType() {
		return this.gradeType;
	}

	public void setGradeType(String gradeType) {
		this.gradeType = gradeType;
	}

	public Float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}

	public Date getLatestUpdateDt() {
		return this.latestUpdateDt;
	}

	public void setLatestUpdateDt(Date latestUpdateDt) {
		this.latestUpdateDt = latestUpdateDt;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
