package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Graphs generated by hbm2java
 */
public class Graphs implements java.io.Serializable {

	private String graphTypes;

	public Graphs() {
	}

	public Graphs(String graphTypes) {
		this.graphTypes = graphTypes;
	}

	public String getGraphTypes() {
		return this.graphTypes;
	}

	public void setGraphTypes(String graphTypes) {
		this.graphTypes = graphTypes;
	}

}
