package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupType generated by hbm2java
 */
public class GroupType implements java.io.Serializable {

	private String groupType;
	private Set personGroups = new HashSet(0);

	public GroupType() {
	}

	public GroupType(String groupType) {
		this.groupType = groupType;
	}

	public GroupType(String groupType, Set personGroups) {
		this.groupType = groupType;
		this.personGroups = personGroups;
	}

	public String getGroupType() {
		return this.groupType;
	}

	public void setGroupType(String groupType) {
		this.groupType = groupType;
	}

	public Set getPersonGroups() {
		return this.personGroups;
	}

	public void setPersonGroups(Set personGroups) {
		this.personGroups = personGroups;
	}

}
