package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Guardian generated by hbm2java
 */
public class Guardian implements java.io.Serializable {

	private String guardianType;
	private String relation;
	private String remarks;
	private Set personDependentDetails = new HashSet(0);

	public Guardian() {
	}

	public Guardian(String guardianType) {
		this.guardianType = guardianType;
	}

	public Guardian(String guardianType, String relation, String remarks,
			Set personDependentDetails) {
		this.guardianType = guardianType;
		this.relation = relation;
		this.remarks = remarks;
		this.personDependentDetails = personDependentDetails;
	}

	public String getGuardianType() {
		return this.guardianType;
	}

	public void setGuardianType(String guardianType) {
		this.guardianType = guardianType;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set getPersonDependentDetails() {
		return this.personDependentDetails;
	}

	public void setPersonDependentDetails(Set personDependentDetails) {
		this.personDependentDetails = personDependentDetails;
	}

}
