package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Marks generated by hbm2java
 */
public class Marks implements java.io.Serializable {

	private MarksId id;
	private Category category;
	private ExamSchedule examSchedule;
	private Person person;
	private Subject subject;
	private Integer marks;
	private Date startDttm;
	private Date updDttm;
	private String remarks;

	public Marks() {
	}

	public Marks(MarksId id, Category category, ExamSchedule examSchedule,
			Person person, Subject subject) {
		this.id = id;
		this.category = category;
		this.examSchedule = examSchedule;
		this.person = person;
		this.subject = subject;
	}

	public Marks(MarksId id, Category category, ExamSchedule examSchedule,
			Person person, Subject subject, Integer marks, Date startDttm,
			Date updDttm, String remarks) {
		this.id = id;
		this.category = category;
		this.examSchedule = examSchedule;
		this.person = person;
		this.subject = subject;
		this.marks = marks;
		this.startDttm = startDttm;
		this.updDttm = updDttm;
		this.remarks = remarks;
	}

	public MarksId getId() {
		return this.id;
	}

	public void setId(MarksId id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public ExamSchedule getExamSchedule() {
		return this.examSchedule;
	}

	public void setExamSchedule(ExamSchedule examSchedule) {
		this.examSchedule = examSchedule;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Integer getMarks() {
		return this.marks;
	}

	public void setMarks(Integer marks) {
		this.marks = marks;
	}

	public Date getStartDttm() {
		return this.startDttm;
	}

	public void setStartDttm(Date startDttm) {
		this.startDttm = startDttm;
	}

	public Date getUpdDttm() {
		return this.updDttm;
	}

	public void setUpdDttm(Date updDttm) {
		this.updDttm = updDttm;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
