package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * MarksSectionWise generated by hbm2java
 */
public class MarksSectionWise implements java.io.Serializable {

	private MarksSectionWiseId id;
	private SubjectSection subjectSection;

	public MarksSectionWise() {
	}

	public MarksSectionWise(MarksSectionWiseId id) {
		this.id = id;
	}

	public MarksSectionWise(MarksSectionWiseId id, SubjectSection subjectSection) {
		this.id = id;
		this.subjectSection = subjectSection;
	}

	public MarksSectionWiseId getId() {
		return this.id;
	}

	public void setId(MarksSectionWiseId id) {
		this.id = id;
	}

	public SubjectSection getSubjectSection() {
		return this.subjectSection;
	}

	public void setSubjectSection(SubjectSection subjectSection) {
		this.subjectSection = subjectSection;
	}

}
