package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MarksId generated by hbm2java
 */
public class MarksId implements java.io.Serializable {

	private String personId;
	private String subjectId;
	private String categoryType;
	private String scheduleId;
	private Date currentDt;

	public MarksId() {
	}

	public MarksId(String personId, String subjectId, String categoryType,
			String scheduleId, Date currentDt) {
		this.personId = personId;
		this.subjectId = subjectId;
		this.categoryType = categoryType;
		this.scheduleId = scheduleId;
		this.currentDt = currentDt;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public String getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Date getCurrentDt() {
		return this.currentDt;
	}

	public void setCurrentDt(Date currentDt) {
		this.currentDt = currentDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MarksId))
			return false;
		MarksId castOther = (MarksId) other;

		return ((this.getPersonId() == castOther.getPersonId()) || (this
				.getPersonId() != null && castOther.getPersonId() != null && this
				.getPersonId().equals(castOther.getPersonId())))
				&& ((this.getSubjectId() == castOther.getSubjectId()) || (this
						.getSubjectId() != null
						&& castOther.getSubjectId() != null && this
						.getSubjectId().equals(castOther.getSubjectId())))
				&& ((this.getCategoryType() == castOther.getCategoryType()) || (this
						.getCategoryType() != null
						&& castOther.getCategoryType() != null && this
						.getCategoryType().equals(castOther.getCategoryType())))
				&& ((this.getScheduleId() == castOther.getScheduleId()) || (this
						.getScheduleId() != null
						&& castOther.getScheduleId() != null && this
						.getScheduleId().equals(castOther.getScheduleId())))
				&& ((this.getCurrentDt() == castOther.getCurrentDt()) || (this
						.getCurrentDt() != null
						&& castOther.getCurrentDt() != null && this
						.getCurrentDt().equals(castOther.getCurrentDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result
				+ (getSubjectId() == null ? 0 : this.getSubjectId().hashCode());
		result = 37
				* result
				+ (getCategoryType() == null ? 0 : this.getCategoryType()
						.hashCode());
		result = 37
				* result
				+ (getScheduleId() == null ? 0 : this.getScheduleId()
						.hashCode());
		result = 37 * result
				+ (getCurrentDt() == null ? 0 : this.getCurrentDt().hashCode());
		return result;
	}

}
