package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * MultipleQuestionAnswer generated by hbm2java
 */
public class MultipleQuestionAnswer implements java.io.Serializable {

	private String questionCode;
	private QuestionsIq questionsIq;
	private Exam exam;
	private String possibleAnswerCode;
	private String answer;

	public MultipleQuestionAnswer() {
	}

	public MultipleQuestionAnswer(QuestionsIq questionsIq) {
		this.questionsIq = questionsIq;
	}

	public MultipleQuestionAnswer(QuestionsIq questionsIq, Exam exam,
			String possibleAnswerCode, String answer) {
		this.questionsIq = questionsIq;
		this.exam = exam;
		this.possibleAnswerCode = possibleAnswerCode;
		this.answer = answer;
	}

	public String getQuestionCode() {
		return this.questionCode;
	}

	public void setQuestionCode(String questionCode) {
		this.questionCode = questionCode;
	}

	public QuestionsIq getQuestionsIq() {
		return this.questionsIq;
	}

	public void setQuestionsIq(QuestionsIq questionsIq) {
		this.questionsIq = questionsIq;
	}

	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	public String getPossibleAnswerCode() {
		return this.possibleAnswerCode;
	}

	public void setPossibleAnswerCode(String possibleAnswerCode) {
		this.possibleAnswerCode = possibleAnswerCode;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
