package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonNativeStudent generated by hbm2java
 */
public class NonNativeStudent implements java.io.Serializable {

	private String id;
	private String language;
	private String state;
	private String country;

	public NonNativeStudent() {
	}

	public NonNativeStudent(String id) {
		this.id = id;
	}

	public NonNativeStudent(String id, String language, String state,
			String country) {
		this.id = id;
		this.language = language;
		this.state = state;
		this.country = country;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
