package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * PerformanceType generated by hbm2java
 */
public class PerformanceType implements java.io.Serializable {

	private String scheduleId;
	private ExamSchedule examSchedule;
	private Subject subject;
	private Double percentage;

	public PerformanceType() {
	}

	public PerformanceType(ExamSchedule examSchedule) {
		this.examSchedule = examSchedule;
	}

	public PerformanceType(ExamSchedule examSchedule, Subject subject,
			Double percentage) {
		this.examSchedule = examSchedule;
		this.subject = subject;
		this.percentage = percentage;
	}

	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public ExamSchedule getExamSchedule() {
		return this.examSchedule;
	}

	public void setExamSchedule(ExamSchedule examSchedule) {
		this.examSchedule = examSchedule;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

}
