package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * PersonId generated by hbm2java
 */
public class PersonId implements java.io.Serializable {

	private String id;
	private String personType;

	public PersonId() {
	}

	public PersonId(String id, String personType) {
		this.id = id;
		this.personType = personType;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonType() {
		return this.personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonId))
			return false;
		PersonId castOther = (PersonId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getPersonType() == castOther.getPersonType()) || (this
						.getPersonType() != null
						&& castOther.getPersonType() != null && this
						.getPersonType().equals(castOther.getPersonType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getPersonType() == null ? 0 : this.getPersonType()
						.hashCode());
		return result;
	}

}
