package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private PersonId id;
	private Category category;
	private String name;
	private String sex;
	private Date dob;
	private Date joinigDate;
	private Date releaseDate;
	private Date creDttm;
	private Set focusAreases = new HashSet(0);
	private Set markses = new HashSet(0);
	private Set personTransactions = new HashSet(0);
	private Set personDependentDetails = new HashSet(0);
	private Set dailyWorks = new HashSet(0);
	private Set personGroups = new HashSet(0);

	public Person()
	{
		category=new Category();
		id = new PersonId();
	}

	public Person(PersonId id, Category category) {
		this.id = id;
		this.category = category;
	}

	public Person(PersonId id, Category category, String name, String sex,
			Date dob, Date joinigDate, Date releaseDate, Date creDttm,
			Set focusAreases, Set markses, Set personTransactions,
			Set personDependentDetails, Set dailyWorks, Set personGroups) {
		this.id = id;
		this.category = category;
		this.name = name;
		this.sex = sex;
		this.dob = dob;
		this.joinigDate = joinigDate;
		this.releaseDate = releaseDate;
		this.creDttm = creDttm;
		this.focusAreases = focusAreases;
		this.markses = markses;
		this.personTransactions = personTransactions;
		this.personDependentDetails = personDependentDetails;
		this.dailyWorks = dailyWorks;
		this.personGroups = personGroups;
	}

	public PersonId getId() {
		return this.id;
	}

	public void setId(PersonId id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getJoinigDate() {
		return this.joinigDate;
	}

	public void setJoinigDate(Date joinigDate) {
		this.joinigDate = joinigDate;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	public Set getFocusAreases() {
		return this.focusAreases;
	}

	public void setFocusAreases(Set focusAreases) {
		this.focusAreases = focusAreases;
	}

	public Set getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set markses) {
		this.markses = markses;
	}

	public Set getPersonTransactions() {
		return this.personTransactions;
	}

	public void setPersonTransactions(Set personTransactions) {
		this.personTransactions = personTransactions;
	}

	public Set getPersonDependentDetails() {
		return this.personDependentDetails;
	}

	public void setPersonDependentDetails(Set personDependentDetails) {
		this.personDependentDetails = personDependentDetails;
	}

	public Set getDailyWorks() {
		return this.dailyWorks;
	}

	public void setDailyWorks(Set dailyWorks) {
		this.dailyWorks = dailyWorks;
	}

	public Set getPersonGroups() {
		return this.personGroups;
	}

	public void setPersonGroups(Set personGroups) {
		this.personGroups = personGroups;
	}

}
