package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonTransaction generated by hbm2java
 */
public class PersonTransaction implements java.io.Serializable {

	private PersonTransactionId id;
	private Person person;
	private String activeClass;
	private String status;
	private String boObject;
	private Date creationDt;
	private Date latestUpdateDt;

	public PersonTransaction() {
	}

	public PersonTransaction(PersonTransactionId id, Person person) {
		this.id = id;
		this.person = person;
	}

	public PersonTransaction(PersonTransactionId id, Person person,
			String activeClass, String status, String boObject,
			Date creationDt, Date latestUpdateDt) {
		this.id = id;
		this.person = person;
		this.activeClass = activeClass;
		this.status = status;
		this.boObject = boObject;
		this.creationDt = creationDt;
		this.latestUpdateDt = latestUpdateDt;
	}

	public PersonTransactionId getId() {
		return this.id;
	}

	public void setId(PersonTransactionId id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getActiveClass() {
		return this.activeClass;
	}

	public void setActiveClass(String activeClass) {
		this.activeClass = activeClass;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBoObject() {
		return this.boObject;
	}

	public void setBoObject(String boObject) {
		this.boObject = boObject;
	}

	public Date getCreationDt() {
		return this.creationDt;
	}

	public void setCreationDt(Date creationDt) {
		this.creationDt = creationDt;
	}

	public Date getLatestUpdateDt() {
		return this.latestUpdateDt;
	}

	public void setLatestUpdateDt(Date latestUpdateDt) {
		this.latestUpdateDt = latestUpdateDt;
	}

}
