package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonAttendence generated by hbm2java
 */
public class PersonAttendence implements java.io.Serializable {

	private String personId;
	private String timeTableId;
	private Date creDttm;
	private String presentAbsent;

	public PersonAttendence() {
	}

	public PersonAttendence(String personId) {
		this.personId = personId;
	}

	public PersonAttendence(String personId, String timeTableId, Date creDttm,
			String presentAbsent) {
		this.personId = personId;
		this.timeTableId = timeTableId;
		this.creDttm = creDttm;
		this.presentAbsent = presentAbsent;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getTimeTableId() {
		return this.timeTableId;
	}

	public void setTimeTableId(String timeTableId) {
		this.timeTableId = timeTableId;
	}

	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	public String getPresentAbsent() {
		return this.presentAbsent;
	}

	public void setPresentAbsent(String presentAbsent) {
		this.presentAbsent = presentAbsent;
	}

}
