package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * PersonDependentDetailId generated by hbm2java
 */
public class PersonDependentDetailId implements java.io.Serializable {

	private String catId;
	private String uniqueId;
	private String guardianType;

	public PersonDependentDetailId() {
	}

	public PersonDependentDetailId(String catId, String uniqueId,
			String guardianType) {
		this.catId = catId;
		this.uniqueId = uniqueId;
		this.guardianType = guardianType;
	}

	public String getCatId() {
		return this.catId;
	}

	public void setCatId(String catId) {
		this.catId = catId;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getGuardianType() {
		return this.guardianType;
	}

	public void setGuardianType(String guardianType) {
		this.guardianType = guardianType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonDependentDetailId))
			return false;
		PersonDependentDetailId castOther = (PersonDependentDetailId) other;

		return ((this.getCatId() == castOther.getCatId()) || (this.getCatId() != null
				&& castOther.getCatId() != null && this.getCatId().equals(
				castOther.getCatId())))
				&& ((this.getUniqueId() == castOther.getUniqueId()) || (this
						.getUniqueId() != null
						&& castOther.getUniqueId() != null && this
						.getUniqueId().equals(castOther.getUniqueId())))
				&& ((this.getGuardianType() == castOther.getGuardianType()) || (this
						.getGuardianType() != null
						&& castOther.getGuardianType() != null && this
						.getGuardianType().equals(castOther.getGuardianType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCatId() == null ? 0 : this.getCatId().hashCode());
		result = 37 * result
				+ (getUniqueId() == null ? 0 : this.getUniqueId().hashCode());
		result = 37
				* result
				+ (getGuardianType() == null ? 0 : this.getGuardianType()
						.hashCode());
		return result;
	}

}
