package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PromoteStudent generated by hbm2java
 */
public class PromoteStudent implements java.io.Serializable {

	private String personId;
	private String fromClassId;
	private String toClassId;
	private Date creDttm;
	private String remarks;

	public PromoteStudent() {
	}

	public PromoteStudent(String personId) {
		this.personId = personId;
	}

	public PromoteStudent(String personId, String fromClassId,
			String toClassId, Date creDttm, String remarks) {
		this.personId = personId;
		this.fromClassId = fromClassId;
		this.toClassId = toClassId;
		this.creDttm = creDttm;
		this.remarks = remarks;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getFromClassId() {
		return this.fromClassId;
	}

	public void setFromClassId(String fromClassId) {
		this.fromClassId = fromClassId;
	}

	public String getToClassId() {
		return this.toClassId;
	}

	public void setToClassId(String toClassId) {
		this.toClassId = toClassId;
	}

	public Date getCreDttm() {
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm) {
		this.creDttm = creDttm;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
