package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * QuestionTable generated by hbm2java
 */
public class QuestionTable implements java.io.Serializable {

	private String questionCode;
	private String questionDescription;
	private String answer;

	public QuestionTable() {
	}

	public QuestionTable(String questionCode) {
		this.questionCode = questionCode;
	}

	public QuestionTable(String questionCode, String questionDescription,
			String answer) {
		this.questionCode = questionCode;
		this.questionDescription = questionDescription;
		this.answer = answer;
	}

	public String getQuestionCode() {
		return this.questionCode;
	}

	public void setQuestionCode(String questionCode) {
		this.questionCode = questionCode;
	}

	public String getQuestionDescription() {
		return this.questionDescription;
	}

	public void setQuestionDescription(String questionDescription) {
		this.questionDescription = questionDescription;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
