package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private String taskCode;
	private String taskStatus;
	private Set dailyWorks = new HashSet(0);

	public Task() {
	}

	public Task(String taskCode) {
		this.taskCode = taskCode;
	}

	public Task(String taskCode, String taskStatus, Set dailyWorks) {
		this.taskCode = taskCode;
		this.taskStatus = taskStatus;
		this.dailyWorks = dailyWorks;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	public Set getDailyWorks() {
		return this.dailyWorks;
	}

	public void setDailyWorks(Set dailyWorks) {
		this.dailyWorks = dailyWorks;
	}

}
