package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * TestTime generated by hbm2java
 */
public class TestTime implements java.io.Serializable {

	private String testCode;
	private String testTime;

	public TestTime() {
	}

	public TestTime(String testCode) {
		this.testCode = testCode;
	}

	public TestTime(String testCode, String testTime) {
		this.testCode = testCode;
		this.testTime = testTime;
	}

	public String getTestCode() {
		return this.testCode;
	}

	public void setTestCode(String testCode) {
		this.testCode = testCode;
	}

	public String getTestTime() {
		return this.testTime;
	}

	public void setTestTime(String testTime) {
		this.testTime = testTime;
	}

}
