package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private String testCode;
	private String testType;

	public Test() {
	}

	public Test(String testCode) {
		this.testCode = testCode;
	}

	public Test(String testCode, String testType) {
		this.testCode = testCode;
		this.testType = testType;
	}

	public String getTestCode() {
		return this.testCode;
	}

	public void setTestCode(String testCode) {
		this.testCode = testCode;
	}

	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

}
