package com.pkg.hibernate;

// Generated 24 Oct, 2013 5:01:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TimeTableCom generated by hbm2java
 */
public class TimeTableCom implements java.io.Serializable {

	private String timeTableId;
	private String replacedSubjectId;
	private String personIdTeacher;
	private Date date;
	private String remarks;

	public TimeTableCom() {
	}

	public TimeTableCom(String timeTableId) {
		this.timeTableId = timeTableId;
	}

	public TimeTableCom(String timeTableId, String replacedSubjectId,
			String personIdTeacher, Date date, String remarks) {
		this.timeTableId = timeTableId;
		this.replacedSubjectId = replacedSubjectId;
		this.personIdTeacher = personIdTeacher;
		this.date = date;
		this.remarks = remarks;
	}

	public String getTimeTableId() {
		return this.timeTableId;
	}

	public void setTimeTableId(String timeTableId) {
		this.timeTableId = timeTableId;
	}

	public String getReplacedSubjectId() {
		return this.replacedSubjectId;
	}

	public void setReplacedSubjectId(String replacedSubjectId) {
		this.replacedSubjectId = replacedSubjectId;
	}

	public String getPersonIdTeacher() {
		return this.personIdTeacher;
	}

	public void setPersonIdTeacher(String personIdTeacher) {
		this.personIdTeacher = personIdTeacher;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
